### ISSUE TITLE
Crash when string contains special characters

### ISSUE THREAD

**Issue by thomasdao** [pilgr/Paper#100]
This library use the key as part of the file name, so if the key contains special character, app will crash. I can reproduce by the code below:

```java
        String content = "Hello";
        Paper.init(this.getApplicationContext());
        String key = "this:key~has&special^@character!@#%*/?.<>";
        Paper.book().write(key, content);
        Log.d("Test", "read: " + Paper.book().read(key));
```

And the app will crash with `java.io.FileNotFoundException: /data/user/0/my.app.package/files/io.paperdb/this:key~has&special^@character!@#%*/?.<>.pt (No such file or directory)`

**Comment by pilgr** [comment]
Thank you for pointing this out. Yes, this known limitation is done for simplicity. Supporting special characters as key values is out of the library scope for now.

**Comment by thomasdao** [comment]
I think it would be easy to support special characters. You can apply URLEncode to the key to set file name, and use URLDecode the file name to retrieve the key back.

However using key as file name still has a limitation - it can't be too long (I think max length is about 255 characters), and also the whole path cannot be 4096 characters.

**Comment by pilgr** [comment]
Yeah, that's true. But those changes would also require adding compatibility for reading data with the older Paper version, handling possible keys overlaps etc. I don't think it worth the effort.
