### ISSUE TITLE
Add support for proper serialization of overridden fields in inheritance hierarchy

### ISSUE THREAD

**Issue by piatt** [pilgr/Paper#103]
If I use an inheritance hierarchy, like the following example,
```kotlin
abstract class Base {
    val id = UUID.randomUUID()
}

open class A(open val prop1: String, open val prop2: String) : Base()

class B(override val prop1: String, override val prop2: String, val prop3: String) : A(prop1, prop2)
```
when I store POJO B in a Book of type Base, it is not serialized properly. On a read of that object, one or more values of B will be null. Upon debugging, using this example: 
```kotlin
val exampleB = B("TEST1", "TEST2", "TEST3")
Paper.book().write(exampleB.id.toString(), exampleB)
```
I found that the content that goes into the PaperTable<Base> looks something like this:

```kotlin
mContent = {
    prop1 = null
    prop2 = null
    prop3 = "TEST3"
    A.prop1 = "TEST1"
    A.prop2 = "TEST2"
    id = "UUID-string"
}   
```
and could also look like this:
```kotlin
mContent = {
    prop1 = null
    prop2 = "TEST2"
    prop3 = "TEST3"
    A.prop1 = "TEST1"
    A.prop2 = null
    id = "UUID-string"
}   
```
Basically, only one version of the property, either the original field or the overridden one is able to store the value of that field. The problem arises after deserialization, when A.prop2 stored, but not B.prop2, since direct field access of B.prop2 returns null.

Upon researching this issue with Kryo, I came across this suggestion from their wiki:

**In case your class inheritance hierarchy contains same named fields, use the CachedFieldNameStrategy.EXTENDED strategy.**
```kotlin
class A {
    String a;
}

class B extends A {
    String a;
}
...
// use `EXTENDED` name strategy, otherwise serialized object can't be deserialized correctly. Attention, `EXTENDED` strategy increases the serialized footprint.
kryo.getFieldSerializerConfig().setCachedFieldNameStrategy(FieldSerializer.CachedFieldNameStrategy.EXTENDED);
```
Cloning your repo and adding this inside of the **createKryoInstance** method of **DbStoragePlainFile.java** fixes my issue. On serialization, all overridden fields as well as the original fields have the same values properly set.
```kotlin
mContent = {
    prop1 = "TEST1"
    prop2 = "TEST2"
    prop3 = "TEST3"
    A.prop1 = "TEST1"
    A.prop2 = "TEST2"
    id = "UUID-string"
}   
```
As stated by Kryo, however, the only downside to adding the extended name strategy is a larger serialization footprint. I am in the process of running some tests of my own to see how much speed and size are affected, but my project would greatly benefit from this change being implemented as soon as possible! Thank you!

**Comment by pilgr** [comment]
cool please share the performance results!
in meanwhile:
* do you have any significant reason to override fields? It looks a bit suspicious.
* in case of this feature added, we should also consider backward data compatibility – the data written with older version should be read with a new version.

**Comment by piatt** [comment]
Thank you for getting back to me! After further investigation, I realized that instead of overriding the fields that my subclasses need in the constructor, I can just pass throwaway values to the super class. I think the problem arose because I was overriding the base class fields AND also initializing the super class with the same values. By changing my class hierarchy example to something like this:
```kotlin
abstract class Base {
    val id = UUID.randomUUID()
}

open class A(val prop1: String, val prop2: String) : Base()

class B(prop1: String, prop2: String, val prop3: String) : A(prop1, prop2)
```
when I store POJO B in a Book of type Base, it is serialized properly. Now using the previous example:
```kotlin
val exampleB = B("TEST1", "TEST2", "TEST3")
Paper.book().write(exampleB.id.toString(), exampleB)

mContent = {
    prop1 = "TEST1"
    prop2 = "TEST2"
    prop3 = "TEST3"
    id = "UUID-string"
}   
```
Feel free to close this issue, as this was more or less an error in kotlin class construction on my part. There are a couple of other features that I would love to see in Paper, like being able to add custom serializers not relegated to a specific class type, in the way Kryo allows you to do it, but I can open a separate request or PR for those later! Thank you for your hard work!

**Comment by pilgr** [comment]
cool! I'll close issue then.
yeah, if you want to extend api to set serializers – please create separate issue.
