### ISSUE TITLE
Caused by java.lang.RuntimeException: Couldn't create Paper dir: null/PostComment

### ISSUE THREAD

**Issue by IzabellaConigliaro** [pilgr/Paper#108]
The Android method Context.getFilesDir() sometimes returns a null value.

(There is a confirmed bug in all pre-4.4 Android devices, which occurs rarely. The reason for the bug is a racing condition in creating app private directory on first launch.

The suggested fix (by Google Android team member) is to try the Context.getFilesDir() method again after first one failed with a "null" return value.)
https://stackoverflow.com/questions/20721649/android-context-getfilesdir-sometimes-returns-root-folder

With the null value, happens a crash in Paper: "Caused by java.lang.RuntimeException: Couldn't create Paper dir: null/PostComment"

Is there a way to fix it?

**Comment by pilgr** [comment]
I'd recommend to catch the exception and to repeat action again. There no many pre-4.4 devices and because issue happen in the platform (not in the Paper itself) I wouldn't like to add such a workaround to the Paper lib.

**Comment by RingoMckraken** [comment]
I've actually experienced this on an Android API 29 emulator.

**Comment by pilgr** [comment]
Fixed and merged to master, included in the new version 2.7.1
