### ISSUE TITLE
PaperDb.init(getApplicationContext()) not called

### ISSUE THREAD

**Issue by rahulabrol** [pilgr/Paper#112]
Caused by: io.paperdb.PaperDbException: Paper.init is not called
as i have mentioned it in my application class...please help?

**Comment by pilgr** [comment]
Did you call Paper.init() prior using any other Paper's api?

**Comment by rahulabrol** [comment]
yes i am calling it from Application class's onCreate method

**Comment by pilgr** [comment]
Do you have some components running in a different android process? It's
too little info to give you some advice.

**Comment by csk2905** [comment]
Please help
io.paperdb.PaperDbException: Paper.init is not called

**Comment by pilgr** [comment]
Please make sure you call `Paper.init()` in UI thread in Application's onCreate method before using database.
