### ISSUE TITLE
[Doubt] Does the changing of model class names due to Proguard-ing effect PaperDb logic?

### ISSUE THREAD

**Issue by abhiank** [pilgr/Paper#113]
Hi, 

I'm working on a library for Android and I've chosen PaperDb for storing the data. I'm concerned about proguard. Will obfuscating and changing the class names and class member of the model classes effect the PaperDb logic?

**Comment by pilgr** [comment]
It shouldn't but better to keep paper and kryo classes untouched for proguard.

**Comment by abhiank** [comment]
Cool. I'll add the model classes to the proguard exclusions.
p.s. Thanks for building this awesome library 👍

**Comment by pilgr** [comment]
You are welcome! Glad you like it.  
What kind of a library do you develop? Is it open sourced?

//Aleksey Masny

**Comment by abhiank** [comment]
Its an analytics view tracking library. No, unfortunately its not open source :/. This is something I'm making for a client of mine.
