### ISSUE TITLE
missing benchmark results for sqlite

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [pilgr/Paper#115]
repo has this:
![image](https://user-images.githubusercontent.com/5357526/35485109-0c9b14a2-0463-11e8-9e3d-a6b01901eded.png)

Where are the results of sqlite?

**Comment by pilgr** [comment]
Not yet measured. Would you like to add one? :)

**Comment by pilgr** [comment]
Not relevant anymore

**Comment by AndroidDeveloperLB** [comment]
How so? Why not update with more updated device?

**Comment by pilgr** [comment]
the sqlite is so different that implementing such comparison test is difficult and since no one made it so far, I don't think it's going to happen anytime soon anyway :)

**Comment by AndroidDeveloperLB** [comment]
So maybe it's time for new benchmark, which will include it and maybe other libraries.
It says Nexus 4...
