### ISSUE TITLE
I am getting a black screen

### ISSUE THREAD

**Issue by andrisole92** [pilgr/Paper#118]
The screen is getting black on Android when I calling:
` Paper.book().write(Constants.ROSTER, roster);`

Does anyone know why?

Thanks

**Comment by pilgr** [comment]
Please provide sufficient info. The issue will remain closed until info is received.

**Comment by andrisole92** [comment]
What info do you need?

**Comment by andrisole92** [comment]
It is also complaining about this, when I am calling Paper.book().write():
`
02-20 15:47:01.474 1500-1513/? E/memtrack: Couldn't load memtrack module
02-20 15:47:01.474 1500-1513/? W/android.os.Debug: failed to get memory consumption info: -1
`

**Comment by pilgr** [comment]
I suppose you are doing writing in UI thread and so your UI thread being locked by the writing process. All long running operations should be called in background thread.
Also I'd suggest to check out the code on real devices (in case if something wrong with emulator)

**Comment by andrisole92** [comment]
Thanks @pilgr, I got to run it in the new Thread.

**Comment by andrisole92** [comment]
However my app is crashing now.
