### ISSUE TITLE
Data not persisted after migrating from v1.1 to v2.1?

### ISSUE THREAD

**Issue by robertdo** [pilgr/Paper#120]
I recently published an update to my app where I upgraded from PaperDb v1.1 to v2.1. Now I'm seeing some reports from users saying that their data got lost after they updated. Should this be happening? Were any necessary steps required in updating PaperDb to preserve the data?

**Comment by pilgr** [comment]
Yes, v 2.1 had an annoying issue which could lead to data loss. It's been fixed in 2.5.
https://github.com/pilgr/Paper/releases/tag/2.5

Did you have any particular reasons to not use the latest 2.6 version?

**Comment by robertdo** [comment]
Ah ok, makes sense. It was just an oversight that I didn't use the latest 2.6 version. So would that v2.1 issue affect every single user, most users, or just a small percentage of users? I'm trying to get an idea of how urgently I need to push a fix.

**Comment by pilgr** [comment]
If I recall correctly it depends on type of data. Unfortunately, if it happened once it may happen for many users with the same structure of data.  


//Aleksey Masny
