### ISSUE TITLE
Android Oreo 8.0 Support

### ISSUE THREAD

**Issue by glocci** [pilgr/Paper#125]
Hi @pilgr 

Thanks for the wonderful library, we are encountering a problem with the new android release.

When we try to read the database we get this error.

`org.objenesis.instantiator.android.Android18Instantiator.findConstructorIdForJavaLangObjectConstructor (Android18Instantiator.java:72)
org.objenesis.instantiator.android.Android18Instantiator.<init> (Android18Instantiator.java:39)
org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf (StdInstantiatorStrategy.java:96)
com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf (Kryo.java:1313)
com.esotericsoftware.kryo.Kryo.newInstantiator (Kryo.java:1127)
com.esotericsoftware.kryo.Kryo.newInstance (Kryo.java:1136)
com.esotericsoftware.kryo.serializers.FieldSerializer.create (FieldSerializer.java:559)
com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read (CompatibleFieldSerializer.java:72)
com.esotericsoftware.kryo.Kryo.readClassAndObject (Kryo.java:816)
com.esotericsoftware.kryo.serializers.CollectionSerializer.read (CollectionSerializer.java:134)
com.esotericsoftware.kryo.serializers.CollectionSerializer.read (CollectionSerializer.java:40)
com.esotericsoftware.kryo.Kryo.readObject (Kryo.java:734)
com.esotericsoftware.kryo.serializers.ObjectField.read (ObjectField.java:125)
com.esotericsoftware.kryo.serializers.FieldSerializer.read (FieldSerializer.java:540)
com.esotericsoftware.kryo.Kryo.readObject (Kryo.java:712)
io.paperdb.DbStoragePlainFile.readTableFile (DbStoragePlainFile.java:248)
io.paperdb.DbStoragePlainFile.readTableFile (DbStoragePlainFile.java:257)
io.paperdb.DbStoragePlainFile.readTableFile (DbStoragePlainFile.java:235)
io.paperdb.DbStoragePlainFile.select (DbStoragePlainFile.java:147)
io.paperdb.Book.read (Book.java:67)`

Have you got any idea on how can I fix it?

**Comment by pilgr** [comment]
Which version of Paper do you use? How often it happens? Could you develop a unit test to reproduce the issue?
