### ISSUE TITLE
compile is obsolete, use implementation now

### ISSUE THREAD

**Issue by ajRiverav** [pilgr/Paper#127]
![image](https://user-images.githubusercontent.com/22076301/39341453-48d38dfe-49a1-11e8-9319-8f20fe96735a.png)

**Comment by Akramhussain4** [comment]
you need to use "implementation" instead of "compile" while adding the dependency in your build.gradle

**Comment by ajRiverav** [comment]
@Akramhussain4 yes. The instructions state to use compile. Pull Request https://github.com/pilgr/Paper/pull/141 fixes this in the instructions.

**Comment by ajRiverav** [comment]
#141 closes this.
