### ISSUE TITLE
dependencies advise

### ISSUE THREAD

**Issue by hiperioncn** [pilgr/Paper#132]
I got the dependence of Paper 2.6

+--- io.paperdb:paperdb:2.6
|    +--- com.esotericsoftware:kryo:4.0.1
|    |    +--- com.esotericsoftware:reflectasm:1.11.3
|    |    |    \--- org.ow2.asm:asm:5.0.4
|    |    +--- com.esotericsoftware:minlog:1.3.0
|    |    \--- org.objenesis:objenesis:2.5.1
|    \--- de.javakaffee:kryo-serializers:0.40
|         \--- com.esotericsoftware:kryo:4.0.0 -> 4.0.1 (*)

and in paperdb's build.gradle 

    compile 'com.esotericsoftware:kryo:4.0.1'
    compile 'de.javakaffee:kryo-serializers:0.40'

Could you change kryo version to 4.0.0

**Comment by pilgr** [comment]
What's the reason?
