### ISSUE TITLE
Proguard sample update

### ISSUE THREAD

**Issue by cloudbank** [pilgr/Paper#135]
Proguard needs kryo entries

**Comment by pilgr** [comment]
I'm using lib in AppDialer since beginning and don't ever seen a need to add kryo into proguard config. Please elaborate if you believe it's still required.

**Comment by cloudbank** [comment]
Hi Oleksii
IDK because I have not looked at that project since 2018 and R8 integration
has moved
my focus off Proguard.
I remember I needed the entry at the time.
Paper is awesome, so maybe I will get back to trying to use it.


Best Regards,


Sabine G. Vogel



*Senior Android Developer *


*@Mobiquity <http://mobiquity.com>*

*MENSA, SWE, Toastmasters*

*415.889.8916*

---------------------------------------------------

**Comment by pilgr** [comment]
That's would be awesome, thanks!
