### ISSUE TITLE
Provide the sample code for read and write data in main thread

### ISSUE THREAD

**Issue by Manikandan92** [pilgr/Paper#146]
Could you please provide the sample app or code using read/write data in main thread, Bacause I'm confusion on your sample app.

**Comment by pilgr** [comment]
It's a trivial question every Android developer should know. It can achieved in numerous ways, starting with AsyncTasks and finishing with Kotlin coroutines. This issue is out of scope of the library.

**Comment by Manikandan92** [comment]
> It's a trivial question every Android developer should know. It can be achieved in numerous ways, starting with AsyncTasks and finishing with Kotlin coroutines. This issue is out of the scope of the library.

When I have using read/write data in UI thread. Please confirm this way is correct??
