### ISSUE TITLE
saving circle object

### ISSUE THREAD

**Issue by MuhammadHassamAli** [pilgr/Paper#154]
can we save google maps circle in Paper?

**Comment by pilgr** [comment]
it depends which fields it has

**Comment by MuhammadHassamAli** [comment]
> it depends which fields it has
whenever i saved circle object it gives error about writing

**Comment by pilgr** [comment]
Yes, paper has been designed to save objects of custom classes under developer's control, not for third party classes like Context, View etc.

**Comment by MuhammadHassamAli** [comment]
hmm ok thank you ;)
