### ISSUE TITLE
Create DB dir Suggest add lock

### ISSUE THREAD

**Issue by vihuela** [pilgr/Paper#159]
KeyLocker.java，Just do the **same key** lock, **but** when **different key** operations, will create a folder **at the same time,** it will report an exception
Solution：DbStoragePlainFile.java，createPaperDir() add lock

**Comment by pilgr** [comment]
Please review the PR with the fix https://github.com/pilgr/Paper/pull/168

**Comment by pilgr** [comment]
Fixed and merged to master, included in the new version 2.7.1
