### ISSUE TITLE
[sample app] AsyncTask or UI Thread Okay?

### ISSUE THREAD

**Issue by johnsintal** [pilgr/Paper#160]
According to the docs, read/write operations should happen in a non-UI thread like an AsyncTask.

However, the sample app show it's in the UI thread.

Can we get away with calling read/write in the UI Thread (for ex. an activity)?

**Comment by pilgr** [comment]
Yeah, thanks for pointing that out, it should be done differently. The `app` has never been referenced as sample app but some people may look into it so it's better be fixed.

**Comment by pilgr** [comment]
I've added async tasks to the sample app in PR #168 It was so fun to write it in 2020 😄
