### ISSUE TITLE
Paper integration for PreferenceFragmentCompat

### ISSUE THREAD

**Issue by Ditscheridou** [pilgr/Paper#162]
Hi! 

Awesome library! It is possible to directly integrate it into a PreferenceFragmentCompat?

**Comment by pilgr** [comment]
Hi! No, Paper doesn't provide such in integration. Do you think that may be valuable? AFAIK `PreferenceFragmentCompat` has been designed to leverage SharedPreferences and using Paper for the preferences is not the primary goal. Paper has been designed to store large objects rather than primitives.
