### ISSUE TITLE
Method to delete all data

### ISSUE THREAD

**Issue by RingoMckraken** [pilgr/Paper#164]
Given a situation where an app uses the global Paper.book() as well as some named ones, is there a way built into paper that can delete all books in one call? My situation is I've been handed a code base where the previous developer has left but there does not seem to be anyway of tracking down the different versions and keys they used to for different versions of the app.

**Comment by pilgr** [comment]
No, Paper doesn't have the function for that. The only way to remove the old data without knowing the names for the "books" is to remove all folders in app's internal storage which has files with `*.pt` extension. But as I said, Paper DB doesn't have the built-in function for that.

**Comment by RingoMckraken** [comment]
Thanks for the response, I have found a (somewhat hacky) way of doing it by iterating through the files directory and attempting to call Paper.book(file.name).destroy() while catching exceptions.
