### ISSUE TITLE
Need a write complete listener.

### ISSUE THREAD

**Issue by Sourav242** [pilgr/Paper#165]
How to know if writting is completed so that it becomes ready to be read? Or need to be wrapped manually with coroutine or work manager?

**Comment by Sourav242** [comment]
How to know if writting is completed so that it becomes ready to be read? Or need to wrapped manually with coroutine or work manager?

**Comment by pilgr** [comment]
All Paper api is synchronous. E.g. as soon as `write` execution completed without exception the reading can be made.
