### ISSUE TITLE
How do I delete a specific item from a book?

### ISSUE THREAD

**Issue by badoyg** [pilgr/Paper#174]
How do I delete an item from a book?

For example, I have this code:

List<String> contacts = new ArrayList<>();
        contacts.add("one");
        contacts.add("two");
        contacts.add("three");

        Paper.book().write("contacts", contacts);

How do I delete only "two" from the book afterwards?

**Comment by pilgr** [comment]
In this case the `contacts` list has to be modified in memory and then written to the book with the same key. Like so:
```
contacts.remove(1);
Paper.book().write("contacts", contacts);
```

People who came with common DB mindset may find this not efficient or weird, but in fact that's way faster and outperforms DBs for common mobile use cases.
