### ISSUE TITLE
Kotlin version of code?

### ISSUE THREAD

**Issue by badoyg** [pilgr/Paper#175]
Can you please give me the Kotlin version of this code?

List<String> retrieved = Paper.book().read("contacts");
        retrieved.remove(address);
        Paper.book().write("contacts", retrieved);

**Comment by AtjonTV** [comment]
That code looks like Java to me, so no Kotlin version there ;D

(`List x =` is Java, `val x =` would be Kotlin)

**Comment by pilgr** [comment]
@badoyg sorry but this question is more about Kotlin usage and not the Paper lib. I'm closing the issue.
