### ISSUE TITLE
Feature proposal: creating listener for data changes

### ISSUE THREAD

**Issue by pwittchen** [pilgr/Paper#18]
Hello,

Thanks for sharing an interesting library!

What do you think about creating a listener for data changes? I think, it's missing, but quite useful feature. We can invoke methods (or single method) from a potential listener interface in `write(...)` and `delete(...)` methods. Let me know about your opinion and I can even create a small PR in a free time.
:-)

Regards,
Piotr

**Comment by pilgr** [comment]
Hello, 

I'd like to keep this library as single-purposed. The main purpose of Paper - to provide fast storage for your Model. I guess model loading, handling data changes, thread handling should be out of scope of Paper.
