### ISSUE TITLE
JCenter getting discontinued

### ISSUE THREAD

**Issue by RomanMinenok** [pilgr/Paper#183]
The library should be migrated to be hosted on Maven Central or another repo as JCenter is getting discontinued.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Any plans regarding that? Thank you.

**Comment by pilgr** [comment]
Library has been moved to Maven Central. Note that group id has been changed to `io.github.pilgr`. 
https://github.com/pilgr/Paper#migration-to-maven-central
