### ISSUE TITLE
Migrate Immediately!!

### ISSUE THREAD

**Issue by NotNotMarshall** [pilgr/Paper#186]
jCenter is currently deprecated and artifacts can only be downloaded till May of 2021, consider migrating to jitpack or maven central. Your library is already breaking.
more info here:
https://developer.android.com/studio/build/jcenter-migration

**Comment by pilgr** [comment]
Library has been moved to Maven Central. Note that group id has been changed to `io.github.pilgr`. 
https://github.com/pilgr/Paper#migration-to-maven-central
