### ISSUE TITLE
minifyEnabled is true and shrinkResources is true getting below error

### ISSUE THREAD

**Issue by ravibuchingari** [pilgr/Paper#189]
io.paperdb.PaperDbException: Couldn't read/deserialize file /data/user/0/com.gvt.smartbill/files/io.paperdb/paired printer.pt for table paired printer

**Comment by jaswant0605** [comment]
found a solution?

**Comment by ravibuchingari** [comment]
Thank you. It is working after changed to gradle version 7.0.1.

**Comment by ravibuchingari** [comment]
Please share me any idea to run same in gradle 7.0.2

**Comment by pilgr** [comment]
The issue has been fixed. Please refer to this task for instructions and give your feedback https://github.com/pilgr/Paper/issues/196
