### ISSUE TITLE
Read operation crashes the app when app uses gradle plugin 7.0.2

### ISSUE THREAD

**Issue by HarshKothari88** [pilgr/Paper#191]
Release an instant fix for this we couldn't update the Gradle plugin due to this issue which affects other libraries. While debugging everything is fine but after generating a signed build apk or aab file the app tends to crash whenever it performs a read operation

**Comment by Vall0n** [comment]
#188

**Comment by pilgr** [comment]
The issue has been fixed. Please refer to this task for instructions and give your feedback https://github.com/pilgr/Paper/issues/196
