### ISSUE TITLE
Compatibility test for 2.7.2

### ISSUE THREAD

**Issue by pilgr** [pilgr/Paper#196]
The version 2.7.2 has been released with the fix for https://github.com/pilgr/Paper/issues/188 and similar nasty issues. 
Now we need to make sure the fix works for everyone and that backward compatibility is in place. 

Please give `2.7.2` a try in your project and leave feedback here:
* Does new version fix the issue with AGP 7.0.2+?
* Does new version read the data saved by the early version `2.7.1` and lower?

**Comment by pilgr** [comment]
No issues found so far, closing the task.

**Comment by BilalZurmati** [comment]
m having deserialization error when apply minifyEnabled=true 
using this version 
...
implementation 'io.github.pilgr:paperdb:2.7.2' 
...

With gradle plugin 7.0.4
