### ISSUE TITLE
How is the serialization working for everything ?

### ISSUE THREAD

**Issue by BobFactory** [pilgr/Paper#205]
Hi, 
Thanks for such an awesome library. I wanted to understand how is the serialization internally working as it seems to serialize almost everything. I tried `LocalDate`, `androidx.compose.ui.graphics.Color`, and `java.time.DayOfWeek` and it seems to work fine. 

However, I have seen an intermittent crash `Invalid primitive conversion from float to int`. I suspect this is because of a data conversion issue, because this only happens during the launch of the app, suggesting it happens when data is fetched from PaperDB. Something even strange is that it resolves itself when debugging as if it needs some more time or an initial delay.  

Are there any data types that I should be aware of while randomly passing for saving into PaperDB?

**Comment by pilgr** [comment]
Hi Bawender,

Paper DB uses [Kryo](https://github.com/EsotericSoftware/kryo) for object graph serialization and deserialization. You may read more in the Kryo project about the limitations. I wouldn't recommend to save any objects structure of which you can't control. Kryo uses reflection a lot and once third-party class internal implementation changes you have a chance that previously saved data won't be readable anymore.
