### ISSUE TITLE
Convert pt file to csv or display database content

### ISSUE THREAD

**Issue by AFgh24** [pilgr/Paper#209]
Hello

I need a solution to convert pt database to a csv file

or a tool to display the data in the pt database

A Windows or Android tool can be really useful
Especially if we want to convert data from a csv file to a pt file or vice versa
A tool for displaying database content or csv conversion

I hope you will show me your way

**Comment by pilgr** [comment]
This is not recommended. However, you can do that when you have the the same classes available in JVM that has been used to write data to pt file. The answer to similar question is here https://github.com/pilgr/Paper/issues/207#issuecomment-1518119309
