### ISSUE TITLE
Dependency not find in Android Studio -> Library Dependency search

### ISSUE THREAD

**Issue by anvesh523** [pilgr/Paper#25]
compile 'io.paperdb:paperdb:1.1'  dependency is not loading in my Android Studio !!!!

Only that Library project we have to add !!!!? 

&

In Demo app nothing was there .... U can try to add few examples, for beginners it will helpful .....

**Comment by pilgr** [comment]
Make sure you specified the repo with dependency. Paper is hosted on jcenter. My ```repositories``` section in ```build.gradle``` looks like:
```
repositories {
    mavenLocal()
    jcenter()
    mavenCentral()
}
```

**Comment by Soroyesodiq** [comment]
Hi pilgr. Am having issues synchronizing my project after adding your implementation 'io.paperdb:paperdb:2.6' dependency.
Below is the error message

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve io.paperdb:paperdb:2.6.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve io.paperdb:paperdb:2.6.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve io.paperdb:paperdb:2.6.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve io.paperdb:paperdb:2.6.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve io.paperdb:paperdb:2.6.
Open File
Show Details
