### ISSUE TITLE
ClassCastException while reading JSON.

### ISSUE THREAD

**Issue by sahildave** [pilgr/Paper#27]
Hey. I am saving and reading a json in a book.

If I read the json back from the book directly it shows a ClassCastException for String to JSONObject

``` java
JSONObject userModelJson = Paper.book(BaseConstants.SESSION_BOOK)
                    .read(BaseConstants.SESSION_START_USER_MODEL);
```

but if I read it as a String and then convert it to JSON using JSONObject API, it succeeds.

``` java
String userModelString = Paper.book(BaseConstants.SESSION_BOOK)
                    .read(BaseConstants.SESSION_START_USER_MODEL);

JSONObject userModelJson = new JSONObject(userModelString);
```

Sample Json

``` json

{
  "address": [
    {
      "address": "full address here",
      "latitude": "0.0",
      "longitude": "0.0"
    }
  ],
  "email": "sample@gmail.com",
  "name": "Sample",
  "phone": "1231231230",
  "username": "sampleuser"
}
```

**Comment by pilgr** [comment]
Could you show more code how do you save data? Do you save JSONObject directly?

**Comment by sahildave** [comment]
I am converting the incoming model (using Retrofit 1.9) to json and saving it. This is done after a null check.

``` java
Paper.book(BaseConstants.SESSION_BOOK).write(BaseConstants.SESSION_START_USER_MODEL,
              new Gson().toJson(userModel, UserModel.class));
```

**Comment by pilgr** [comment]
The {a[er is designed to operate with model classes directly using much more efficient syrialization then json. You should try something like ```
Paper.book(BaseConstants.SESSION_BOOK).write(BaseConstants.SESSION_START_USER_MODEL,
              userModel);
```

And do read userModel instance directly.

**Comment by sahildave** [comment]
Ok. Will try this and report.

**Comment by sahildave** [comment]
No issues yet. Closing.
