### ISSUE TITLE
android:allowBackup should not be used in library

### ISSUE THREAD

**Issue by raviteja06** [pilgr/Paper#28]
Error:Execution failed for task ':app:processInternalConfigDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:36:9-36
	is also present at [io.paperdb:paperdb:1.1] AndroidManifest.xml:11:18-44 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:34:5-101:19 to override.

even lint suggestion will not help.

**Comment by arok** [comment]
+1

**Comment by showang** [comment]
+1
