### ISSUE TITLE
Couldn't read/deserialize file

### ISSUE THREAD

**Issue by AmrMohammed89** [pilgr/Paper#32]
Couldn't read/deserialize file /data/user/0/files/io.paperdb/full_user.pt for table  full_user

**{
  "data": {
    "__v": "18",
    "_id": "************",
    "contact_moods": [],
    "contacts": {
      "registered_contacts": [
        {
          "_id": "*******",
          "checked": false,
          "color": 0,
          "phone_number": "+*********"
        },
        {
          "_id": "**********",
          "checked": false,
          "color": 0,
          "phone_number": "+****************"
        },
        {
          "_id": "********************",
          "checked": false,
          "color": 0,
          "phone_number": "+*********************"
        }
      ]
    },
    "country": "EG",
    "custom_moods": [
      {
        "_id": "569f66b9a3479e330e47e28b",
        "_mizo": {
          "_gif": "/happy.mp4",
          "_id": "569e3ecf0bd1d68f5d9e3314",
          "_owner": "66609fe0-beb3-11e5-99d0-553ae763ee48",
          "checked": false,
          "created_at": "2016-01-19T13:49:03.070Z",
          "is_preset": false,
          "is_published": false,
          "liked_by": [],
          "reported_by": [],
          "tags": [],
          "text": "happy",
          "textAttr": {
            "text_color_index": -16777216,
            "text_position_x": 20,
            "text_position_y": 20,
            "text_size_index": 1
          },
          "upload_state": "COMPLETED",
          "used_by": []
        },
        "contacts": [],
        "groups": [],
        "is_enabled": true,
        "is_global": false,
        "name": "Feeling happy"
      },
      {
        "_id": "569f6ebea3479e330e47e293",
        "_mizo": {
          "_gif": "/89d4a24f-76f3-41fa-a747-b2a5ff340dd4-1453287075597.jpg",
          "_id": "569f67b4a3479e330e47e28f",
          "_owner": "66609fe0-beb3-11e5-99d0-553ae763ee48",
          "checked": false,
          "created_at": "2016-01-20T10:55:48.818Z",
          "is_preset": false,
          "is_published": false,
          "liked_by": [],
          "reported_by": [],
          "tags": [],
          "text": "",
          "textAttr": {
            "text_color_index": -16777216,
            "text_position_x": 0,
            "text_position_y": 0,
            "text_size_index": 1
          },
          "upload_state": "COMPLETED",
          "used_by": []
        },
        "contacts": [],
        "groups": [],
        "is_enabled": true,
        "is_global": false,
        "name": ""
      }
    ],
    "gcm_reg_id": "*********",
    "groups": [],
    "phone_number": "+2*********",
    "public_mood": {
      "_mizo": {
        "_gif": "/cold.mp4",
        "_id": "569f6ebea3479e330e47e292",
        "_owner": "66609fe0-beb3-11e5-99d0-553ae763ee48",
        "checked": false,
        "created_at": "2016-01-20T11:25:46.566Z",
        "is_preset": false,
        "is_published": false,
        "liked_by": [],
        "reported_by": [],
        "tags": [],
        "text": "",
        "textAttr": {
          "text_color_index": -16777216,
          "text_position_x": 0,
          "text_position_y": 0,
          "text_size_index": 1
        },
        "upload_state": "COMPLETED",
        "used_by": []
      },
      "is_enabled": true,
      "is_global": false,
      "name": ""
    },
    "settings": {
      "is_mood_visible_for_contacts_only": false,
      "is_sync_on_wifi_only": false,
      "language": "EN"
    },
  },
  "isNew": false,
  "message": "success"
}**

**Comment by felipeleusin** [comment]
You should save the bitmap as a byte array and then decode after you load it from Paper.
