### ISSUE TITLE
Custom storage location

### ISSUE THREAD

**Issue by leisim** [pilgr/Paper#33]
Please add a method which allows selecting a custom location for books? (e.g. on the sdcard)

**Comment by yanglichuan** [comment]
metoo

**Comment by haichaoyuan** [comment]
me too

**Comment by MatthewTrout** [comment]
+1 , would be useful to set the root directory of the paper instance, probably as a configuration value to `Paper.init()`.  I might look at this if I get a moment.

**Comment by pilgr** [comment]
Fixed in #2.6
