### ISSUE TITLE
Some change listener

### ISSUE THREAD

**Issue by emce** [pilgr/Paper#36]
It would be good to implement some change listener, which would be listening to any change made on storage...

**Comment by Enorio** [comment]
If you write something with the same key value, does the Paper overwrite what was there or just create a new data file?
For example:
Paper.book().write("city", "String");
Paper.book().write("city", "Other string");
And if i do String city = Paper.book().read("city"), what do i get?

**Comment by pilgr** [comment]
I don't think it should be part of the library. The good implementation would require thread management as a listener should be fired in UI thread. But library implemented in a way to not handle UI threads itself. I would recommend building the layer on the top of the Paper to care about safe loading in a background thread, caching and watch changes.
