### ISSUE TITLE
RxJava support

### ISSUE THREAD

**Issue by rafakob** [pilgr/Paper#38]
Hi, have you thought about adding RxJava support?

**Comment by pilgr** [comment]
Yeah, could be useful

**Comment by rafakob** [comment]
I know there is this https://github.com/cesarferreira/RxPaper/blob/master/rxpaper/src/main/java/com/cesarferreira/rxpaper/RxPaper.java

but it's not maintained anymore.

**Comment by LordRaydenMK** [comment]
You can check out https://github.com/pakoito/RxPaper It is an Rx wrapper for this library.

**Comment by pilgr** [comment]
Please use separate libs providing bindings for rxJava 1 and 2 
https://github.com/pakoito/RxPaper
https://github.com/pakoito/RxPaper2
