### ISSUE TITLE
Couldn't create Paper dir

### ISSUE THREAD

**Issue by AlexanderShtanko** [pilgr/Paper#48]
Hi!
Sometimes I have an exception: Exception java.lang.RuntimeException: Couldn't create Paper dir.
What can I do to avoid this exception?

**Comment by pilgr** [comment]
Hi! I don't think you can do much about it, as file system prevents call to create a dir. E.g. if user run out of space.

**Comment by pilgr** [comment]
@AlexanderShtanko could you tell why did you close this issue? You can't reproduce it? Or you found problem in some other place, not relates to the Paper?
