### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by AndreasBackx** [pilgr/Paper#5]
Paper looks very interesting, but I have some questions about how the file access works. It says random file access is rapid on flash storage. What happens if 2 async tasks read the file and write to the file making the first write to the file obsolete? The second write was based on the result before the first write when it probably should've been based on that after the first write. Does Paper handle these issues or do we have to make sure ourselves that that doesn't happen?

**Comment by pilgr** [comment]
Every file operation is synchronized by _storage_ instance 
https://github.com/pilgr/Paper/blob/master/paperdb/src/main/java/io/paperdb/DbStoragePlainFile.java#L112
Paper has only one _storage_ instance. So all put/get/etc operations are synchronized.
In your example the thread which get access first will save data first. And second one rewrite old data after first one is done. 

Doesn't matter you use Paper or any data storage, it should be your responsibility to write correct data in correct order. Paper just controls that more than one parallel write/read operations never happened.

**Comment by pilgr** [comment]
Do you think the issue is exist anyway? Or we can close the issue?

**Comment by AndreasBackx** [comment]
We can, it was just a question wondering whether Paper handled it this way or not.
