### ISSUE TITLE
Retrieve files saved by Paper

### ISSUE THREAD

**Issue by chitgoks** [pilgr/Paper#52]
Is there a way to retrieve the files saved by Paper? My scenario is that i would like to store the saved files in the cloud to serve as backup.

want to add that i did see a get file something method in one of the classes but it is private.

**Comment by pilgr** [comment]
Yes, you can do this manually as Paper doesn't have the API for that. Every `Book` is stored as files in a separate folder. The path to this folder is created here 
https://github.com/pilgr/Paper/blob/master/paperdb/src/main/java/io/paperdb/DbStoragePlainFile.java#L263
where `dbName` is the name of your `Book`. The default book name is `io.paperdb`.
https://github.com/pilgr/Paper/blob/master/paperdb/src/main/java/io/paperdb/Paper.java#L27

I created an issue #53 to make such API.

**Comment by chitgoks** [comment]
hi pilgr. thank you

would it be alright to request an API call to retrieve a specific file? like, making the existing method public instead of private.

because there may be files that do not need updating, hence getting all the files as a single zip file may not be the best ideal way to sync. it may be alright to start with but once there are so many files, as in many ... then there'd be no sense to update those that do not need updating.

**Comment by pilgr** [comment]
Sure, makes sense
