### ISSUE TITLE
Add API to export/import Book content

### ISSUE THREAD

**Issue by pilgr** [pilgr/Paper#53]
For the purpose of backup, add Book API for export/import its content.

**Comment by Pinaz9** [comment]
Is this API implemented yet? If not, what is the status.

**Comment by pilgr** [comment]
not implemented yet, but you can manually copy *.pt files from app's directory
https://github.com/pilgr/Paper/blob/master/paperdb/src/main/java/io/paperdb/DbStoragePlainFile.java#L286
