### ISSUE TITLE
ObjectStreamClass.newInstance(Class<?>, long) is private API and will be removed in a future Android release.

### ISSUE THREAD

**Issue by drivfe** [pilgr/Paper#58]
Warning I get in logcat after every Book.write()

I guess this is actually a Kryo problem?

**Comment by pilgr** [comment]
What kind of class are you trying to save?

**Comment by drivfe** [comment]
The usual (String, integers, floats, boolean). Others are classes such as Date, HashMaps and Enums.

Btw this is on paperdb 1.5

**Comment by pilgr** [comment]
I can't reproduce this on a device running API23

**Comment by drivfe** [comment]
Only happens API24 for me.

**Comment by pakoito** [comment]
FWIW: https://android.googlesource.com/platform/libcore/+/987c9ca%5E!/

**Comment by drivfe** [comment]
I've been trying to reproduce it in an example project but nothing.

Been trying with different variations of Maps with Enums/Classes as their keys/values but no luck yet.

**Comment by Nlpilip** [comment]
hello pilgr,
i also get this error when im reading/writing the following class:
```
public class Driver extends ModelBase{
    private String fname;
    private String lname;
    private String phoneNumber;
    private String emailAddress;
    private String recoveryKey;
    private String activeVehicleId;
    private String connectionId;
    private Vehicle activeVehicle;
```

```
public class Vehicle extends ModelBase implements Serializable{
    private String brand;
    private String licensePlate;
    private String status;
    private GPS gps;
    private String driverId;
    private String companyId;
    private String type;
    private String model;
    private Integer maxPassengers;
    private String gpsTime;
```

hope this can help with fixing the warning message

**Comment by arunkumar9t2** [comment]
I am currently getting this warning on API 25. I ll see if I can create a sample project.

**Comment by miszmaniac** [comment]
I can confirm I'm getting this errors

**Comment by FrescoFlacko** [comment]
I can also confirm I am getting this error, and I'm getting a SIGSEGV signal 11 crash also.

**Comment by raviteja06** [comment]
+1

**Comment by TormundsMember** [comment]
+1 on Android 7.1.1 (SDK 25)

**Comment by ervinmartirosyan** [comment]
+1 on Android 7.0
```
public class Profile {
    public final String ssid;
    public final String ip;
    public final int port;
}
```

**Comment by pilgr** [comment]
good news, guys!

please check out the version 2.1-rc1 and let me know if it all good. I'll publish the release after that.
`compile 'io.paperdb:paperdb:2.1-rc1'`

Some details if you curious. 

Paper uses Kryo for serialization and deserialization objects. https://github.com/EsotericSoftware/kryo
This makes Paper so fast. 

Kryo uses Objenesis lib to instantiate objects in a most efficient, platform specific way. 
https://github.com/easymock/objenesis

Objenesis used some of the private ObjectStream methods to instantiate objects.  

Starting from Android N Google uses Open JDK which doesn't contain (obviously) those private methods. And Google added those private methods with a warning which we all seen. 
https://android.googlesource.com/platform/libcore/+/987c9ca%5E!/
Please check out the NOTE in that diff, they made this to not break Paper (actually Objenesis) haha

Objenesis fixed this in v 2.3 
https://github.com/easymock/objenesis/releases/tag/2.3
But Kryo 4.0 (latest stable release) still use Objenesis 2.2. 

So I fixed this in a way by forcibly specifying the updated Objenesis version in the Paper dependencies. 
https://github.com/pilgr/Paper/commit/a090a23879ca4fbcf52008a021e7fbe3229b9e11
This should work until Kryo will be updated with new dependency.

To speed up this I made a PR to Kryo 
https://github.com/EsotericSoftware/kryo/pull/514

All this means for you is you should update Paper version to 2.1 (2.1-rc1 for now) and that's it. Enjoy! :)

**Comment by Neferetheka** [comment]
Thanks pilgr for addressing all our concerns and fixing the issue!

**Comment by obuiron** [comment]
@pilgr 
[Kryo 4.0.1](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-4.0.1) has been released.
No longer need to force version of Objenesis in Paper's `build.gradle`.
