### ISSUE TITLE
All read write calls should be safe to use in UI thread.

### ISSUE THREAD

**Issue by ramanclabs** [pilgr/Paper#60]
It will be super easy to use if all the read write calls are in UI thread means background processing done by library itself.

**Comment by pakoito** [comment]
It shouldn't be the base library's responsibility to be opinionated about threads. I have a wrapper that does that for you: https://github.com/pakoito/RxPaper

**Comment by pilgr** [comment]
I believe that UI loading and cashing should be done outside of the
library. This can keep lib fit and thin.

For example you can use RxPaper where Paper API wrapped up with RxJava. Or
AsyncAwait lib if you brave enough to use not yet released Kotlin 1.1 :)
