### ISSUE TITLE
How can be sure the data is safe

### ISSUE THREAD

**Issue by chowaikong** [pilgr/Paper#61]
Since Paper is saving data on local storage, so I want to make sure the data is safe by Paper saved. It's Paper safe?

**Comment by chowaikong** [comment]
And I have root my phone, go to the /data/data/app-package/files/io.paperdb folder, those .pt files can open with text viewer easily, also those values clearly has no secret.

**Comment by pilgr** [comment]
Sure, Paper works like any other database where data stored in internal but readable format. You can take a look for Hawk which supports data encryption.
