### ISSUE TITLE
Init lib automatically using content provider

### ISSUE THREAD

**Issue by pilgr** [pilgr/Paper#62]
https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

**Comment by pakoito** [comment]
If it's up for debate I'd vote against it. It's a heavy handed hack in exchange for what's a line of code that'll throw an exception if missing, which can happen only once per project tops. Paper is geared towards intermediate-advanced users that'll read and understand the requirements, which is not the target audience Google intends for Firebase. The change also breaks flow for multi-process apps, and takes control away from the implementer.

**Comment by pilgr** [comment]
Yeah, I read about all drawbacks, they don't look like showstoppers for me. For multi-process apps Paper can throw an exception like it's now so devs can init it in custom Application class. The init section is not very important for devs to pay so much attention for it. `Paper.init()` is only about capturing app context. And I'm so lazy to create Application classes and register it in AndroidManifest that I would use safe (!) tricks in order to provide better and more convenient API for everyone :)

**Comment by fiskurgit** [comment]
Couple of months old this but... I prefer explicit initialisation to this hack. A ContentProvider should be used to provide content, it's a misuse of the API to use it to get around calling init(); 

I know the example is on googleblog but it seems like bad practice.

**Comment by pilgr** [comment]
Ok, agreed with you guys. Let's close it 🎉
