### ISSUE TITLE
why remove rewrite the method getDbPath  in DbStoragePlainFile.java 

### ISSUE THREAD

**Issue by haichaoyuan** [pilgr/Paper#63]
I used pagerdb-1.0.1, it is well except some problems.
Now I want to upgrade to pagerdb-2.0, I find that i can not change paper cache dir to sd card.
Why do you delete the code about interface PaperContextListener?

**Comment by pilgr** [comment]
Could you provide your old code example which doesn't work now?

**Comment by haichaoyuan** [comment]
Thank fo your response, :)
## here is the code from DbStoragePlainFile.java in pagerdb-1.0.1 ：
```

private String getDbPath(Context context, String dbName) {
        if(context instanceof PaperContextListener) {
            PaperContextListener c = (PaperContextListener)context;
            if(c.getPaperCacheDir() == null) {
                throw new NullPointerException("paper cache dir is null");
            } else {
                return c.getPaperCacheDir() + File.separator + dbName;
            }
        } else {
            return context.getFilesDir() + File.separator + dbName;
        }
    }
```


## now,this is the new code in pagerdb-2.0

```
private String getDbPath(Context context, String dbName) {
            return context.getFilesDir() + File.separator + dbName;
   }

```

So that, I can not store date to sd card.

Thank you again.

**Comment by pilgr** [comment]
Ha, I'm curious how did you get that code from like 1.0.1 version? Here is the correct one from 1.0
https://github.com/pilgr/Paper/blob/1.0/paperdb/src/main/java/io/paperdb/DbStoragePlainFile.java#L227
I close this issue as it's not an issue but more like feature request #33

**Comment by haichaoyuan** [comment]
Thank you for your help :+1: ! 
Remenber to call me when you add the feature.
