### ISSUE TITLE
Speed up concurrent read/writes for different keys

### ISSUE THREAD

**Issue by hiperioncn** [pilgr/Paper#65]
I saved a list use Paper.
The size of list about 5000, just a simple bean.
When I read the list from Paper, about spend 15s,
Is it very slow for this case?
The bean like this:
public class Comments implements Serializable {
    private static final long serialVersionUID = -1291325341797562204L;
    private String Comment;
    private boolean flag;
    private String user;
    private Integer UserID;
    private Long TS;
    private String id;
}

**Comment by pilgr** [comment]
I would expect few seconds to read this. How much write takes? How is it on other devices?

**Comment by hiperioncn** [comment]
Write is fast, about 10ms. I test these operates on LG G3 and Nexus 6P, the result is same.
Read about 15s, write about 10ms.

**Comment by hiperioncn** [comment]
Could you tell me what's your purpose in below code?
`@Override
    public synchronized <E> E select(String key) {
        assertInit();
        final File originalFile = getOriginalFile(key);
        final File backupFile = makeBackupFile(originalFile);
        if (backupFile.exists()) {
            //noinspection ResultOfMethodCallIgnored
            originalFile.delete();
            //noinspection ResultOfMethodCallIgnored
            backupFile.renameTo(originalFile);
        }
        if (!exist(key)) {
            return null;
        }
        return readTableFile(key, originalFile);
    }`
Why do you make a backupFile, then delete orginalFile, then rename backupFile to orginalFile. Not do any other operate?
And still read from orginalFile?
I can't understand why do you do this. 
Thank you.

**Comment by pilgr** [comment]
This is done to avoid data corruption. Existing backup file means last writing attempt was failed - so we do read from backup file and use it as original file for next read. This code is very similar how google implemented read/write in `SharedPreference` class.

**Comment by hiperioncn** [comment]
Thanks for your explain.
Do you hava any ideas about read slow?

**Comment by pilgr** [comment]
Not for now. Please write a unit test or gist with full working code to reproduce.

**Comment by hiperioncn** [comment]
**Here is a test case, you can run it in your project.
At the same time on two different key of read and write operations.
Read a simple key "key1" must be wait write key "persons" finish.**

```
package io.paperdb.multithread;
import android.test.AndroidTestCase;
import android.util.Log;
import org.junit.Before;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import io.paperdb.Paper;
import io.paperdb.testdata.Person;
import io.paperdb.testdata.TestDataGenerator;
import static android.support.test.InstrumentationRegistry.getTargetContext;

public class ReadSlowTest extends AndroidTestCase {
  boolean finished = false;
  //The bean of person is too simply, so set large size.
  List<Person> insertedPersons = TestDataGenerator.genPersonList(100000);
  @Before
  public void setUp() throws Exception {
    Paper.clear(getTargetContext());
    Paper.init(getTargetContext());
    Paper.book().write("key1","ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789");
  }
  public void testReadSlow() throws Exception {
    ExecutorService mExecutor = Executors.newFixedThreadPool(10);
    mExecutor.submit(getInsertRunnable());
    mExecutor.submit(getSelectRunnable());
    while (!finished){//wait for test finish}
  }
  private Runnable getInsertRunnable() {
    return new Runnable() {
      @Override
      public void run() {
        long s1 = System.currentTimeMillis();
        Log.d(">>>>>>>", "write persons start");
        Paper.book().write("persons", insertedPersons);
        long s2 = System.currentTimeMillis();
        Log.d(">>>>>>>", "write persons end spend:" + (s2 - s1) + "ms");
        finished = true;
      }
    };
  }
  private Runnable getSelectRunnable() {
    return new Runnable() {
      @Override
      public void run() {
        long s1 = System.currentTimeMillis();
        Log.d(">>>>>>>", "read key1 start");
        Paper.book().read("key1");
        long s2 = System.currentTimeMillis();
        Log.d(">>>>>>>", "read key1 end spend:" + (s2 - s1) + "ms");
      }
    };
  }
}
```

**Logcat output:**

03-09 16:06:37.071 1472-1511/io.paperdb.test D/>>>>>>>: write persons start
03-09 16:06:37.074 1472-1512/io.paperdb.test D/>>>>>>>: read key1 start
03-09 16:06:48.438 1472-1511/io.paperdb.test D/>>>>>>>: write persons end spend:11367ms
03-09 16:06:48.444 1472-1512/io.paperdb.test D/>>>>>>>: read key1 end spend:11370ms

**Comment by pilgr** [comment]
Hey, I got what is the problem. The all read/write operations for the given book are synchronized by the DbStoragePlainFile instance. This means only one operation to read/write is allowed per book. I see a way to improve this by making lock not by whole storage instance, but per key.

**Comment by hiperioncn** [comment]
That's a good news.
Waiting for the new feature.

**Comment by hiperioncn** [comment]
Make a pull request yesterday. Hope it can help your fix this issue.

**Comment by hiperioncn** [comment]
Any question about this pull request?

**Comment by pilgr** [comment]
Probably I missed this commit, could you create a PR?
