### ISSUE TITLE
io.paperdb.PaperDbException: Couldn't rename file

### ISSUE THREAD

**Issue by madhanmallow** [pilgr/Paper#77]
What is the reason for this exception and how to handle this?

**Comment by pilgr** [comment]
Could you provide a more detailed stack trace?

**Comment by madhanmallow** [comment]
W/System.err: io.paperdb.PaperDbException: Couldn't rename file /data/user/0/com.redtaxi.driver/files/io.paperdb/travelTime.pt to backup file /data/user/0/
W/System.err:     at io.paperdb.DbStoragePlainFile.insert(DbStoragePlainFile.java:117)
W/System.err:     at io.paperdb.Book.write(Book.java:36)
W/System.err:     at com.redtaxi.driver.fragments.RTTripBillFragment.removePrefsValues(RTTripBillFragment.java:158)
W/System.err:     at com.redtaxi.driver.fragments.RTTripBillFragment.onCreateView(RTTripBillFragment.java:67)
W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
W/System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by pilgr** [comment]
Paper renames the original file to file "*.bak" on writing attempt to have a way to recover in case if writing is failed. 
https://github.com/pilgr/Paper/blob/master/paperdb/src/main/java/io/paperdb/DbStoragePlainFile.java#L115
The issues may happen because the original data file is locked for some reasons. Do you use the same Paper instance for all read/write operations? Using different Paper instances may cause data inconsistency and crashes like this.

How often does issue happen? Can you provide a test case or a sample code to reproduce it?

**Comment by madhanmallow** [comment]
I'm using Paper.book().read() and Paper.book().write() throughout the app. My app also have two services running in background which also uses the above methods. Will this cause the issue?

**Comment by pilgr** [comment]
Two services running in one process or in different processes? Paper doesn't support data consistency when accessed from different processes.

**Comment by madhanmallow** [comment]
They are running in two separate processes. How to handle this? Please suggest me a solution.

**Comment by pilgr** [comment]
Keep all the code accessing Paper in one process, let's say the main process where Paper can be accessed from activities and services. This main process should expose Binder interface with all the necessary API to get data. So another process can use Binder interface to access data without knowing anything about Paper underhood.
[Service with Paper, Process1 ](BINDER)<-[Another service, Process2]
