### ISSUE TITLE
crash during 1.5 => 2.1 transition

### ISSUE THREAD

**Issue by martinbonnin** [pilgr/Paper#87]
I made a small android app to reproduce there: https://github.com/martinbonnin/TestPaper

it fails with:

        Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 99
        Serialization trace:
        ingredients (testpaper.mbonnin.net.testpaper.Recipe)
        mContent (io.paperdb.PaperTable)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137)

**Comment by pilgr** [comment]
What I found for now is crash happens not because of Kryo update bu because of 
update de.javakaffee:kryo-serializers:0.33 -> 0.40

**Comment by pilgr** [comment]
My previous assumption was wrong. Crash happens after update com.esotericsoftware:kryo:3.0.3->4.0.0. (previously lesser kryo version didn't take effect because of transitive dependency for kryo-serializers)

**Comment by pilgr** [comment]
you were right, thanks! changing `getFieldSerializerConfig().setOptimizedGenerics` for existing kryo instance doesn't take effect. Using new temporary kryo object in compatibility mode solves the issue. Fix is on the way.

**Comment by pilgr** [comment]
Fixed in https://github.com/pilgr/Paper/commit/408164c8dc2153b60df92b6c0e66471026b4648d
(forgot to mention in commit message)

**Comment by martinbonnin** [comment]
Thanks ! Do you know when the next release is planned ? As far as I'm concerned, the sooner, the better as I'm stuck on 1.5 with the potential crash on Android N for now.

**Comment by pilgr** [comment]
I hope to make it today or tomorrow.

**Comment by martinbonnin** [comment]
Awesome, thanks !

**Comment by pilgr** [comment]
Could you check out new version 2.5? It’s already published to the maven repo but not yet released publicly. Thanks!


//Aleksey Masny
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by martinbonnin** [comment]
Works fine, thanks!
