### ISSUE TITLE
PaperDB instance is null

### ISSUE THREAD

**Issue by Manikandan92** [pilgr/Paper#89]
I've custom class to create PaperDB instance. I use that class's constructor to initialize the PaperDB instance like below
 public PaperDB(Activity activity) {
        this.context = activity;
        Paper.init(this.context);
    }

    public PaperDB(Context context) {
        this.context = context;
        Paper.init(this.context);
    }

In a fragment's onCreateView method, I create an instance for the custom PaperDB class. For example,

private PaperDB myDB;
....
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
.....
 myDB = new PaperDB(getActivity());
....
}

When I access this instance in one of the fragment's method it returns null. I also didn't assign null to myDB anywhere in the fragment class. How to resolve this issue?

**Comment by pilgr** [comment]
I don't understand why do you need a separate PaperDB class, it doesn't have anything common with Paper class and Paper instance. Your problem is not related to this project. Sorry, but I have to close the issue.
