### ISSUE TITLE
Hey! Does your app use Paper? How many users it has?

### ISSUE THREAD

**Issue by pilgr** [pilgr/Paper#92]
Share your experience, I would be glad to know more details how lib is applied for your cases? 🙃
Do you mind for putting app name on the front page?

**Comment by powerthazan** [comment]
I am using Paper with Firebase Datastore to locally Store Data. I like Paper due to is simplicity. Thanks for your Great library!

**Comment by powerthazan** [comment]
This [Engineering Blog](https://play.google.com/store/apps/details?id=com.hneati.engineeringblog) Android App is using 'Paper' to Store user's Read-later bookmarks, then display on listview!

**Comment by drivfe** [comment]
I use Paper to store favorite players in [Rocket Friend](https://play.google.com/store/apps/details?id=com.drivfe.rocketfriend&hl=en).

**Comment by Neferetheka** [comment]
I've been using it to store all data in my game [Baseball Legends 2](https://play.google.com/store/apps/details?id=com.aerilys.baseball.android.next).

I've also used it in big apps at work, but can't tell you which ones on Github ;)

**Comment by ArtemGorobets** [comment]
I'm using Paper in [Hryvnia](https://play.google.com/store/apps/details?id=ua.co.hryvnia) to store serialized responses as a cached data:)
