### ISSUE TITLE
Feature: Opportunity add TTL to record

### ISSUE THREAD

**Issue by N-i-p-o-l** [pilgr/Paper#99]
Example: Paper.book().write("city", "Lund").ttl(3600) //3600 sec
Now we can't read value after 3600 sec. It will return null

**Comment by N-i-p-o-l** [comment]
At this moment I use wrapper for this. But I have one drawback. I remove expired data when I read from db. I need automatic remove expired data with ttl (as redis do)

**Comment by pilgr** [comment]
To be honest I don't think this feature should be a part of any database. You can design your data model in order to serve a purpose like yours. For example, you can keep a timestamp along with your data and check it on reading and so on. So I'm closing this feature request.
